name: "TranDir"
author: "Pavel Dostál"
description: "Czech Transport Directory"

port: 3000
production: true
url: "http://trandir.pdostal.cz"

markdown: rdiscount
permalink: pretty

exclude: ["Gemfile*", "Capfile", "lib/", "config/", "README.md"]

assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: sass
  sources:
  - _assets/css/skeleton/css
  - _assets/css
  - _assets/js
